#!/usr/bin/python
# -*- coding: UTF-8 -*-
import argparse
import ploy

parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers(dest="command",
    title='subcommands')

version = subparsers.add_parser('version',
    help='Show ploy software version.')

start = subparsers.add_parser('start',
    help='Start the ploy web interface.')

args = parser.parse_args()

if args.command == 'version':
    import pkg_resources
    print(pkg_resources.get_distribution("ploy").version)
elif args.command == 'start':
    import ploy.webapp
    ploy.webapp.start()


